### PR TITLE
Number of spaces as a gaussian distribution

### PR DESCRIPTION
**Pull request by ErezVolk**
Thanks for a wonderful tool! I've been using it for two days, and already I feel safer!

This little pull request includes two main tweaks:
- I ran `black` on the code, because, you know.
- I added an option to make the number of spaces sampled from a Gaussian distribution, to facilitate adoption in the scientific community.

### CODE REVIEW

**Comment by ishefi** [comment]
I liked your changes, but where are the unittests?

Also, I think some unittests are not passing right now with the new changes.

**Comment by ErezVolk** [comment]
Unit whats?

**Comment by ErezVolk** [comment]
Fine, fine. I threw in a CI step for you.

**Comment by ishefi** [comment]
Thanks!
but it seems like your unittest fails from time to time...
```
self = <tests.test_codistancing.CodistancingTestCase testMethod=test_data_science>

    def test_data_science(self):
        reformatter = Reformatter(mean=4, std=1)
        actual = reformatter.reformat_string(
            "for i in range(5): "
            "for j in range(9): "
            "for k in range(3): "
            "print(i*j+k)"
        )
        blanks = re.split(r"\S+", actual)
        lens = [len(b) for b in blanks if b]
>       self.assertEqual(statistics.median(lens), 4)
E       AssertionError: 3 != 4

test_codistancing.py:143: AssertionError
```

**Comment by ErezVolk** [comment]
Sorry, that's how we do it in academia.

**Pull request merged**
